[[shader]]
id = "s_menu_background"
vertex = "assets/shaders/menu/background.vert"
fragment = "assets/shaders/menu/background.frag"

[[font_mtsdf]]
id = "f_consolas"
image = "assets/images/fonts/consolas.sdf.png"
data = "assets/images/fonts/consolas.csv"

[[font_mtsdf]]
id = "f_lcdsolid"
image = "assets/images/fonts/lcdsolid.sdf.png"
data = "assets/images/fonts/lcdsolid.csv"

[[font_mtsdf]]
id = "f_consolas_bold"
image = "assets/images/fonts/consolas_bold.sdf.png"
data = "assets/images/fonts/consolas_bold.csv"

[[audio]]
id = "a_blip3"
path = "assets/audio/blip3.mp3"
predecode = true

[[audio]]
id = "a_darkness_music"
path = "assets/audio/menu/darkness music.mp3"
predecode = true

[[audio]]
id = "a_static2"
path = "assets/audio/menu/static2.mp3"
predecode = true

[[texture]]
id = "t_newspaper"
path = "assets/images/misc/NEWSPAPER.png"

[[texture_array]]
id = "t_menu_background"
textures = [
    { path = "assets/images/menu/background/1.png" },
    { path = "assets/images/menu/background/2.png" },
    { path = "assets/images/menu/background/3.png" },
    { path = "assets/images/menu/background/4.png" }
]

[[texture_array]]
id = "t_static"
textures = [
    { path = "assets/images/static/12.png" },
    { path = "assets/images/static/13.png" },
    { path = "assets/images/static/14.png" },
    { path = "assets/images/static/15.png" },
    { path = "assets/images/static/16.png" },
    { path = "assets/images/static/17.png" },
    { path = "assets/images/static/18.png" },
    { path = "assets/images/static/20.png" }
]

[[texture_array]]
id = "t_blip"
textures = [
    { path = "assets/images/misc/night_bars/1.png",  gpu_format = "rgba", format = "rgba" },
    { path = "assets/images/misc/night_bars/2.png",  gpu_format = "rgba", format = "rgba" },
    { path = "assets/images/misc/night_bars/3.png",  gpu_format = "rgba", format = "rgba" },
    { path = "assets/images/misc/night_bars/4.png",  gpu_format = "rgba", format = "rgba" },
    { path = "assets/images/misc/night_bars/5.png", gpu_format = "rgba", format = "rgba" },
    { path = "assets/images/misc/night_bars/6.png", gpu_format = "rgba", format = "rgba" },
    { path = "assets/images/misc/night_bars/7.png", gpu_format = "rgba", format = "rgba" },
    { path = "assets/images/misc/night_bars/8.png", gpu_format = "rgba", format = "rgba" },
    { path = "assets/images/misc/night_bars/9.png", gpu_format = "rgba", format = "rgba" }
]

[[texture_array]]
id = "t_menu_blip"
textures = [
    { path = "assets/images/misc/white_bars/1.png" },
    { path = "assets/images/misc/white_bars/2.png" },
    { path = "assets/images/misc/white_bars/3.png" },
    { path = "assets/images/misc/white_bars/4.png" },
    { path = "assets/images/misc/white_bars/5.png" },
    { path = "assets/images/misc/white_bars/6.png" },
    { path = "assets/images/misc/white_bars/7.png" }
]
