[[texture_array]]
id = "t_office"
textures = [
    { path = "assets/images/night/office/1.png" },
    { path = "assets/images/night/office/2.png" },
    { path = "assets/images/night/office/3.png" },
    { path = "assets/images/night/office/4.png" },
    { path = "assets/images/night/office/5.png" }
]

[[texture]]
id = "t_mute_call"
path = "assets/images/night/MUTE_CALL_BUTTON.png"

[[shader]]
id = "s_office"
vertex = "assets/shaders/office/background.vert"
fragment = "assets/shaders/office/background.frag"

[[audio]]
id = "a_office_buzz"
path = "assets/audio/night/Buzz_Fan_Florescent2.mp3"
predecode = true
