name: Build on Latest Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git \
                                   libasound2-dev libpulse-dev \
                                   libx11-dev libxext-dev libxrandr-dev \
                                   libxcursor-dev libxi-dev libxinerama-dev \
                                   libgl1-mesa-dev

      - name: Build SDL3
        run: |
          git clone https://github.com/libsdl-org/SDL.git
          cd SDL
          cmake -S . -B . -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          sudo make install
          cd ../..

      - name: Build SDL3_mixer
        run: |
          git clone https://github.com/libsdl-org/SDL_mixer.git
          cd SDL_mixer
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          sudo make install
          cd ../..

      - name: Build Debug
        run: make bud

      - name: Build Release
        run: make bur