name: Build on Latest Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Upgrade CMake
        uses: lukka/get-cmake@latest


      - name: Build SDL3
        shell: pwsh
        run: |
          git clone https://github.com/libsdl-org/SDL.git
          cd SDL

          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release --parallel
          cmake --build build
          cmake --install build --prefix "${env:GITHUB_WORKSPACE}\sdl-install"

      - name: Build SDL3_mixer
        shell: pwsh
        run: |
          git clone https://github.com/libsdl-org/SDL_mixer.git
          cd SDL_mixer

          cmake -S . -B build -G Ninja `
            -DCMAKE_BUILD_TYPE=Release --parallel`
            -DSDL3_DIR="${env:GITHUB_WORKSPACE}\sdl-install\lib\cmake\SDL3"

          cmake --build build
          cmake --install build --prefix "${env:GITHUB_WORKSPACE}\sdl-install"

      - name: Build Debug
        run: |
          cmake -B build -S . --preset windows-base`
            -DSDL3_DIR="${env:GITHUB_WORKSPACE}\sdl-install\lib\cmake\SDL3"`
            -DSDL3_MIXER_DIR="${env:GITHUB_WORKSPACE}\sdl-install\lib\cmake\SDL_mixer"
          cmake --build build --config Debug --parallel
          cmake --install build --prefix out

      - name: Build Release
        run: |
          cmake -B build -S . --preset windows-base`
            -DSDL3_DIR="${env:GITHUB_WORKSPACE}\sdl-install\lib\cmake\SDL3"`
            -DSDL3_MIXER_DIR="${env:GITHUB_WORKSPACE}\sdl-install\lib\cmake\SDL_mixer"
          cmake --build build --config Release --parallel
          cmake --install build --prefix out
          
